In [14]:
!pip install ydata_profiling

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 359.5/359.5 kB 4.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.8/104.8 kB 4.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 686.1/686.1 kB 8.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 9.0 MB/s eta 0:00:00
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27080 sha256=0c57bf03b337dfdcdb8f8b41e41959b864b946ec00d28dc123d32f05a9117231
  Stored in directory: /root/.cache/pip/wheels/dd/91/29/a79cecb328d01739e64017b6fb9a1ab9d8cb1853098ec5966d
Successfully built htmlmin


In [1]:
# 1.Generate meaningful features from existing
# data.
# 2.Use techniques like PCA or feature
# importance to select the most important
# features.
# Optimize feature sets for improved model
# performance.

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import ydata_profiling as ydp
import seaborn as sns

In [3]:
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Main_flow(Data science)/heart.csv")

In [4]:
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [26]:
X = data.drop('target', axis=1)
y = data['target']

In [23]:
data['cp'].value_counts()

cp
0    497
2    284
1    167
3     77
Name: count, dtype: int64

In [25]:
columns = data.columns
n = len(columns)
for i in range(n):
  print(data[columns[i]].value_counts())

age
58    68
57    57
54    53
59    46
52    43
51    39
56    39
62    37
60    37
44    36
64    34
41    32
63    32
67    31
61    31
55    30
65    27
43    26
42    26
53    26
66    25
45    25
48    23
46    23
50    21
47    18
49    17
35    15
39    14
70    14
68    12
38    12
71    11
40    11
69     9
37     6
34     6
29     4
76     3
77     3
74     3
Name: count, dtype: int64
sex
1    713
0    312
Name: count, dtype: int64
cp
0    497
2    284
1    167
3     77
Name: count, dtype: int64
trestbps
120    128
130    123
140    107
110     64
150     55
138     45
128     39
125     38
160     36
112     30
132     28
118     24
108     21
124     20
135     20
145     17
134     17
152     17
170     15
122     14
100     14
136     11
126     10
180     10
142      9
115      9
105      9
146      8
148      7
178      7
94       7
144      6
102      6
154      4
117      4
165      4
200      4
114      4
123      4
192      3
106      3
104      3
129      3
174   

In [6]:
data.shape

(1025, 14)

In [8]:
data.size

14350

In [9]:
data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [10]:
data.corr()

age       sex        cp  trestbps      chol       fbs  \
age       1.000000 -0.103240 -0.071966  0.271121  0.219823  0.121243   
sex      -0.103240  1.000000 -0.041119 -0.078974 -0.198258  0.027200   
cp       -0.071966 -0.041119  1.000000  0.038177 -0.081641  0.079294   
trestbps  0.271121 -0.078974  0.038177  1.000000  0.127977  0.181767   
chol      0.219823 -0.198258 -0.081641  0.127977  1.000000  0.026917   
fbs       0.121243  0.027200  0.079294  0.181767  0.026917  1.000000   
restecg  -0.132696 -0.055117  0.043581 -0.123794 -0.147410 -0.104051   
thalach  -0.390227 -0.049365  0.306839 -0.039264 -0.021772 -0.008866   
exang     0.088163  0.139157 -0.401513  0.061197  0.067382  0.049261   
oldpeak   0.208137  0.084687 -0.174733  0.187434  0.064880  0.010859   
slope    -0.169105 -0.026666  0.131633 -0.120445 -0.014248 -0.061902   
ca        0.271551  0.111729 -0.176206  0.104554  0.074259  0.137156   
thal      0.072297  0.198424 -0.163341  0.059276  0.100244 -0.042177   
target   -0.229324 -0.279501  0.434854 -0.138772 -0.099966 -0.041164   

           restecg   thalach     exang   oldpeak     slope        ca  \
age      -0.132696 -0.390227  0.088163  0.208137 -0.169105  0.271551   
sex      -0.055117 -0.049365  0.139157  0.084687 -0.026666  0.111729   
cp        0.043581  0.306839 -0.401513 -0.174733  0.131633 -0.176206   
trestbps -0.123794 -0.039264  0.061197  0.187434 -0.120445  0.104554   
chol     -0.147410 -0.021772  0.067382  0.064880 -0.014248  0.074259   
fbs      -0.104051 -0.008866  0.049261  0.010859 -0.061902  0.137156   
restecg   1.000000  0.048411 -0.065606 -0.050114  0.086086 -0.078072   
thalach   0.048411  1.000000 -0.380281 -0.349796  0.395308 -0.207888   
exang    -0.065606 -0.380281  1.000000  0.310844 -0.267335  0.107849   
oldpeak  -0.050114 -0.349796  0.310844  1.000000 -0.575189  0.221816   
slope     0.086086  0.395308 -0.267335 -0.575189  1.000000 -0.073440   
ca       -0.078072 -0.207888  0.107849  0.221816 -0.073440  1.000000   
thal     -0.020504 -0.098068  0.197201  0.202672 -0.094090  0.149014   
target    0.134468  0.422895 -0.438029 -0.438441  0.345512 -0.382085   

              thal    target  
age       0.072297 -0.229324  
sex       0.198424 -0.279501  
cp       -0.163341  0.434854  
trestbps  0.059276 -0.138772  
chol      0.100244 -0.099966  
fbs      -0.042177 -0.041164  
restecg  -0.020504  0.134468  
thalach  -0.098068  0.422895  
exang     0.197201 -0.438029  
oldpeak   0.202672 -0.438441  
slope    -0.094090  0.345512  
ca        0.149014 -0.382085  
thal      1.000000 -0.337838  
target   -0.337838  1.000000

In [17]:
ydp.ProfileReport(data)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [18]:
data[['cp','thal','target']]

cp  thal  target
0      0     3       0
1      0     3       0
2      0     3       0
3      0     3       0
4      0     2       0
...   ..   ...     ...
1020   1     2       1
1021   0     3       0
1022   0     2       0
1023   0     2       1
1024   0     3       0

[1025 rows x 3 columns]

from matplotlib import pyplot as plt
_df_0['cp'].plot(kind='hist', bins=20, title='cp')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['thal'].plot(kind='hist', bins=20, title='thal')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['target'].plot(kind='hist', bins=20, title='target')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3.plot(kind='scatter', x='cp', y='thal', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='thal', y='target', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5['cp'].plot(kind='line', figsize=(8, 4), title='cp')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_6['thal'].plot(kind='line', figsize=(8, 4), title='thal')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_7['target'].plot(kind='line', figsize=(8, 4), title='target')
plt.gca().spines[['top', 'right']].set_visible(False)

In [38]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import r_regression

X_selection = SelectKBest(r_regression, k=10).fit_transform(X, y)

In [40]:
pd.DataFrame(X_selection).head()

0    1    2      3      4    5    6      7    8    9
0  52.0  1.0  0.0  125.0  212.0  0.0  1.0  168.0  2.0  3.0
1  53.0  1.0  0.0  140.0  203.0  1.0  0.0  155.0  0.0  3.0
2  70.0  1.0  0.0  145.0  174.0  0.0  1.0  125.0  0.0  3.0
3  61.0  1.0  0.0  148.0  203.0  0.0  1.0  161.0  2.0  3.0
4  62.0  0.0  0.0  138.0  294.0  1.0  1.0  106.0  1.0  2.0

In [37]:
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [42]:
from sklearn.feature_selection import chi2

chi2_corr = chi2(X, y)

In [43]:
chi2_corr

(array([ 81.42536762,  24.37365008, 217.82392171,  45.97406854,
        110.72336371,   1.47754962,   9.73934262, 650.00849349,
        130.47092725, 253.65346109,  33.67394807, 210.62591949,
         19.37346461]),
 array([1.82006646e-019, 7.93466060e-007, 2.69806406e-049, 1.19828657e-011,
        6.80314928e-026, 2.24158301e-001, 1.80365390e-003, 2.22466183e-143,
        3.23231840e-030, 4.14929994e-057, 6.51676273e-009, 1.00301831e-047,
        1.07490299e-005]))

In [44]:
from sklearn.feature_selection import f_classif

f_corr = f_classif(X, y)

In [45]:
f_corr

(array([ 56.78513485,  86.6897071 , 238.55845714,  20.08735284,
         10.32615227,   1.73635185,  18.838205  , 222.79953804,
        242.88388949, 243.45077988, 138.67939282, 174.87707812,
        131.80299644]),
 array([1.06772202e-13, 7.52383119e-20, 1.56320576e-48, 8.23301498e-06,
        1.35257125e-03, 1.87896749e-01, 1.56410343e-05, 9.96297084e-46,
        2.69493169e-49, 2.14133804e-49, 4.12205348e-30, 5.69914842e-37,
        8.78119168e-29]))

In [49]:
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
sfs = SequentialFeatureSelector(knn, n_features_to_select=5, direction="forward")
sfs.fit(X, y)
X_selection = sfs.transform(X)

In [48]:
pd.DataFrame(X_selection).head()

0      1    2
0  212.0  168.0  2.0
1  203.0  155.0  0.0
2  174.0  125.0  0.0
3  203.0  161.0  1.0
4  294.0  106.0  3.0

In [56]:
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier

knn = DecisionTreeClassifier()
rfe = RFE(knn, n_features_to_select=5)
rfe.fit(X, y)
X_selection = rfe.transform(X)

In [57]:
pd.DataFrame(X_selection).head()

0    1      2    3    4
0  52.0  0.0  212.0  1.0  2.0
1  53.0  0.0  203.0  3.1  0.0
2  70.0  0.0  174.0  2.6  0.0
3  61.0  0.0  203.0  0.0  1.0
4  62.0  0.0  294.0  1.9  3.0

In [60]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X_selection, y, test_size=0.3, random_state=42)

In [68]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)
pre = model.predict(X_test)

In [69]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, pre)
mse

0.2662337662337662

In [70]:
from sklearn.model_selection import GridSearchCV

In [72]:
param_grid = {"C": [0.1, 1, 10], "penalty": ["l1", "l2"]}

grid_search = GridSearchCV(model , param_grid, cv=5, scoring="accuracy")
grid_search.fit(X_train,y_train)

# Print the best hyperparameters and the corresponding score
print("Best hyperparameters:", grid_search.best_params_)
print("Best score:", grid_search.best_score_)

# Train the model with the best hyperparameters
model_best = grid_search.best_estimator_
model_best.fit(X_train,y_train)

Best hyperparameters: {'C': 0.1, 'penalty': 'l2'}
Best score: 0.7977855477855478


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:378: FitFailedWarning: 
15 fits failed out of a total of 30.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 54, in _check_solver
    raise ValueError(
ValueError: Solve

LogisticRegression(C=0.1)

In [73]:
ypre = model_best.predict(X_test)

In [75]:
print(mean_squared_error(y_test, ypre))

0.2727272727272727


In [76]:
from sklearn.decomposition import PCA
import numpy as np

# Create a random dataset with 1000 samples and 50 features
X = np.random.rand(1000, 50)

# Create a PCA object with 2 components
pca = PCA(n_components=2)

# Fit the PCA model to our dataset
pca.fit(X)

# Transform our dataset into the new lower-dimensional space
X_pca = pca.transform(X)

In [78]:
pd.DataFrame(X_pca).head()

0         1
0  0.544912 -0.368610
1  0.318017  0.177583
2 -0.707539 -0.208569
3  0.205884 -0.554043
4 -0.522239  0.327896